## this will ultimately be a singularity container
FROM nvidia/cuda:11.2.0-cudnn8-devel-ubuntu20.04
MAINTAINER Robert Settlage

ENV LANG en_US.UTF-8
ENV TZ=America/New_York

RUN apt-get update -y && apt-get install -y wget gnupg && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y software-properties-common && \
    add-apt-repository ppa:graphics-drivers/ppa

# Intall Anaconda
RUN echo 'export PATH=/anaconda3/bin:$PATH' > /etc/profile.d/anaconda.sh && \
    wget https://repo.continuum.io/archive/Anaconda3-2021.05-Linux-x86_64.sh -O /anaconda.sh && \
    /bin/bash /anaconda.sh -b -p /anaconda3 && \
    rm anaconda.sh

ENV PATH=/anaconda3/bin:$PATH
ENV PATH=/anaconda3/envs/DEEPLABCUT/bin:$PATH

##### Install Deeplabcut and its dependencies #####
RUN apt-get -y install libcanberra-gtk-module libcanberra-gtk3-module

COPY ./DEEPLABCUT.yaml ./
RUN conda env create -f DEEPLABCUT.yaml
SHELL ["conda", "run", "-n", "DEEPLABCUT", "/bin/bash", "-c"]
RUN conda install tensorflow-gpu==1.15.0 && \
    pip install deeplabcut

# make quick test script
RUN echo "#!/bin/bash" > run.sh && \
    echo "source activate DEEPLABCUT" >> run.sh && \
    echo "python -m deeplabcut" >> /run.sh 
